export enum ApiEndpoints {
  COMMUNITY = 'communities',
  COMMUNITY_ANSWERS = 'community/answers',
  ARTICLES = 'articles',
  REGISTER = 'auth/register-user',
  VERIFY = 'verify',
  CHECK_TOKEN = 'auth/check-token',
  REPEAT_VERIFY = 'verify/send-code',
  PREMIUM_CODE_CHECK = 'exam/premium/verify-entry-code',
  LOGIN = 'auth/login-user',
  EXAMS = 'exam',
  EXAM_QUESTIONS = 'exam/free/questions',
  EXAM_PROFESSION = 'exam-profession',
  EXAM_PREMIUM_FORM = 'exam/premium/request',
  EXAM_PREMIUM_QUESTIONS = 'exam/premium/questions',
  EXAM_HAS_CHANCE = 'exam/premium/valid_entry_code',
  EXAM_FREE_RESULT = 'exam/free/result',
  EXAM_PREMIUM_RESULT = 'exam/premium/result',
  COMMUNITY_FILTER = 'community/search?',
  RESULT_FEEDBACK = 'customer-feedback',
  COMMUNITY_COUNT = 'community/read-info-count',
  ARTICLE_COUNT = 'article/read-info-count',
  LEADERSHIP_BOARD = 'leadership-board',
  LEADERSHIP_BOARD_2 = 'leadership-board/out?',
  COMMUNITY_DETAILS = 'community-reply/read-info?',
  LOGOUT = 'auth/logout',
  MOCK_EXAM = 'mock-exam/list?',
  IMAGE = 'image',
  RESULT_PERCENTAGE = 'result/percentage',
  USER_PROFILE = 'user-profile',
  USER_PROFILE_EDIT = '/user-profile/edit',
  USER_PROFILE_SEND_CODE = 'user-profile/send-verification-code',
  SEND_VERIFICATION_CODE = 'auth/send-verification-code',
  UPDATE_PASSWORD = 'auth/reset-password',
  USER_PROFILE_UPDATE_PASSWORD = 'user-profile/update-password',
  GAMIFICATION_EXAM_START = 'gamification-exam/start',
  GAMIFICATION_EXAM_SUBMIT = 'gamification-exam/submit',
  GAMIFICATION_EXAM_NEXT_QUESTION = 'gamification-exam/next',
  GAMIFICATION_EXAM_USER_LEVEL = 'gamification-exam/user-level',
  GAMIFICATION_EXAM_FINISH = 'gamification-exam/finish',
  GAMIFICATION_EXAM_LEADERBOARD = 'gamification-exam/leaderboard',
  GAMIFICATION_EXAM_PARTICIPATED = 'gamification-exam/user-is-participated',
  APPLY_FOR_TRAINING = 'apply-for-training',
}

export enum ApiResponseTypes {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}
